// GENERATED by scripts/gen-components.mjs from components.def.mjs — do not edit.
export declare const controlHeight: 'calc(2 * var(--space-8) + var(--font-sm) * var(--leading-snug) + 2px)'

export declare const button: {
  readonly base: {
    readonly display: 'inline-flex'
    readonly alignItems: 'center'
    readonly gap: 'var(--space-6)'
    readonly cursor: 'pointer'
    readonly fontFamily: 'inherit'
    readonly lineHeight: 'var(--leading-snug)'
    readonly whiteSpace: 'nowrap'
    readonly textDecoration: 'none'
  }
  readonly sizes: {
    readonly xs: {
      readonly padding: 'var(--space-2) var(--space-6)'
      readonly fontSize: 'var(--font-xs)'
      readonly borderRadius: 'var(--radius-xs)'
      readonly fontWeight: '600'
    }
    readonly sm: {
      readonly padding: 'var(--space-4) var(--space-10)'
      readonly fontSize: 'var(--font-sm)'
      readonly borderRadius: 'var(--radius-sm)'
      readonly fontWeight: '600'
    }
    readonly md: {
      readonly padding: 'var(--space-8) var(--space-14)'
      readonly fontSize: 'var(--font-sm)'
      readonly borderRadius: 'var(--radius-md)'
      readonly fontWeight: '500'
    }
  }
  readonly variants: {
    readonly primary: {
      readonly background: 'var(--primary)'
      readonly color: 'var(--on-primary)'
      readonly border: '1px solid var(--primary)'
    }
    readonly secondary: {
      readonly background: 'var(--surface)'
      readonly color: 'var(--text-heading)'
      readonly border: '1px solid var(--border)'
    }
    readonly ghost: {
      readonly background: 'transparent'
      readonly color: 'var(--text-muted)'
      readonly border: '1px solid transparent'
    }
    readonly danger: {
      readonly background: 'var(--danger)'
      readonly color: 'var(--on-primary)'
      readonly border: '1px solid var(--danger)'
    }
    readonly dangerOutline: {
      readonly background: 'var(--surface)'
      readonly color: 'var(--danger-text)'
      readonly border: '1px solid var(--danger-border)'
    }
    readonly admin: {
      readonly background: 'var(--admin-soft)'
      readonly color: 'var(--admin-text)'
      readonly border: '1px solid var(--admin-border)'
    }
  }
  readonly onBar: {
    readonly secondary: {
      readonly background: 'transparent'
      readonly color: 'var(--bar-text)'
      readonly border: '1px solid var(--bar-btn-border)'
    }
    readonly ghost: {
      readonly background: 'transparent'
      readonly color: 'var(--bar-text-muted)'
      readonly border: '1px solid transparent'
    }
    readonly admin: {
      readonly background: 'var(--admin-tint)'
      readonly color: 'var(--bar-text)'
      readonly border: '1px solid var(--admin-tint)'
    }
    readonly dangerOutline: {
      readonly background: 'transparent'
      readonly color: 'var(--bar-text)'
      readonly border: '1px solid var(--danger)'
    }
  }
}

export declare const input: {
  readonly base: {
    readonly padding: 'var(--space-8) var(--space-10)'
    readonly borderWidth: '1px'
    readonly borderStyle: 'solid'
    readonly borderColor: 'var(--border)'
    readonly borderRadius: 'var(--radius-md)'
    readonly fontSize: 'var(--font-sm)'
    readonly background: 'var(--surface)'
    readonly color: 'var(--text)'
    readonly outline: 'none'
    readonly boxSizing: 'border-box'
    readonly fontFamily: 'inherit'
    readonly lineHeight: 'var(--leading-snug)'
  }
  readonly sm: {
    readonly padding: 'var(--space-4) var(--space-8)'
    readonly borderRadius: 'var(--radius-sm)'
    readonly fontSize: 'var(--font-xs)'
  }
  readonly lg: {
    readonly padding: 'var(--space-8) var(--space-12)'
    readonly fontSize: 'var(--font-lg)'
  }
  readonly textarea: {
    readonly resize: 'vertical'
    readonly lineHeight: 'var(--leading-normal)'
    readonly minHeight: '4.5rem'
  }
  readonly mono: {
    readonly fontFamily: 'var(--mono-font)'
  }
  readonly admin: {
    readonly borderColor: 'var(--admin-border)'
  }
  readonly invalid: {
    readonly borderColor: 'var(--danger)'
  }
  readonly readOnly: {
    readonly background: 'var(--surface-hover)'
    readonly color: 'var(--text-soft)'
  }
}

export declare const badge: {
  readonly base: {
    readonly display: 'inline-flex'
    readonly alignItems: 'center'
    readonly gap: 'var(--space-4)'
    readonly borderRadius: 'var(--radius-pill)'
    readonly fontWeight: '600'
    readonly lineHeight: 'var(--leading-normal)'
    readonly whiteSpace: 'nowrap'
    readonly fontVariantNumeric: 'tabular-nums'
  }
  readonly sizes: {
    readonly sm: {
      readonly padding: 'var(--space-1) var(--space-6)'
      readonly fontSize: 'var(--font-xxs)'
    }
    readonly md: {
      readonly padding: 'var(--space-2) var(--space-8)'
      readonly fontSize: 'var(--font-xs)'
    }
  }
  readonly tones: {
    readonly neutral: {
      readonly soft: 'var(--surface-hover)'
      readonly text: 'var(--text-soft)'
      readonly solid: 'var(--text-soft)'
      readonly onSolid: 'var(--on-primary)'
    }
    readonly primary: {
      readonly soft: 'var(--primary-soft)'
      readonly text: 'var(--primary-strong)'
      readonly solid: 'var(--primary)'
      readonly onSolid: 'var(--on-primary)'
    }
    readonly success: {
      readonly soft: 'var(--success-soft)'
      readonly text: 'var(--success-text)'
      readonly solid: 'var(--success)'
      readonly onSolid: 'var(--on-primary)'
    }
    readonly danger: {
      readonly soft: 'var(--danger-soft)'
      readonly text: 'var(--danger-text)'
      readonly solid: 'var(--danger)'
      readonly onSolid: 'var(--on-primary)'
    }
    readonly warning: {
      readonly soft: 'var(--warning-soft)'
      readonly text: 'var(--warning-text)'
      readonly solid: 'var(--warning)'
      readonly onSolid: 'var(--warning-on-bar)'
    }
    readonly info: {
      readonly soft: 'var(--info-soft)'
      readonly text: 'var(--info)'
      readonly solid: 'var(--info)'
      readonly onSolid: 'var(--on-primary)'
    }
    readonly accent: {
      readonly soft: 'var(--accent-soft)'
      readonly text: 'var(--accent-text)'
      readonly solid: 'var(--accent)'
      readonly onSolid: 'var(--on-primary)'
    }
  }
  readonly outlineBorder: 'var(--border)'
}

export declare const alert: {
  readonly base: {
    readonly padding: 'var(--space-8) var(--space-12)'
    readonly borderRadius: 'var(--radius-md)'
    readonly fontSize: 'var(--font-sm)'
    readonly lineHeight: 'var(--leading-snug)'
    readonly whiteSpace: 'pre-wrap'
  }
  readonly tones: {
    readonly error: {
      readonly bg: 'var(--danger-soft)'
      readonly fg: 'var(--danger-text)'
      readonly border: 'var(--danger-border)'
    }
    readonly warning: {
      readonly bg: 'var(--warning-soft)'
      readonly fg: 'var(--warning-text)'
      readonly border: 'var(--warning)'
    }
    readonly success: {
      readonly bg: 'var(--success-soft)'
      readonly fg: 'var(--success-text)'
      readonly border: 'var(--success)'
    }
    readonly info: {
      readonly bg: 'var(--surface-muted)'
      readonly fg: 'var(--text-heading)'
      readonly border: 'var(--border)'
    }
  }
}

export declare const card: {
  readonly base: {
    readonly background: 'var(--surface)'
    readonly border: '1px solid var(--border)'
    readonly borderRadius: 'var(--radius-lg)'
    readonly padding: 'var(--space-24)'
    readonly boxShadow: 'var(--shadow-sm)'
  }
  readonly admin: {
    readonly border: '1px solid var(--admin-border)'
  }
}

export declare const panel: {
  readonly plain: {
    readonly background: 'var(--surface)'
    readonly borderWidth: '1px'
    readonly borderStyle: 'solid'
    readonly borderColor: 'var(--border)'
    readonly borderRadius: 'var(--radius-md)'
    readonly minWidth: '0'
  }
  readonly muted: {
    readonly background: 'var(--surface-muted)'
    readonly borderRadius: 'var(--radius-md)'
    readonly minWidth: '0'
  }
  readonly inset: {
    readonly background: 'var(--bg)'
    readonly borderRadius: 'var(--radius-md)'
    readonly minWidth: '0'
  }
  readonly pad: {
    readonly padding: 'var(--space-10) var(--space-12)'
  }
}

export declare const actionBar: {
  readonly display: 'flex'
  readonly alignItems: 'center'
  readonly flexWrap: 'wrap'
  readonly gap: 'var(--space-8)'
  readonly padding: 'var(--space-8) var(--space-14)'
  readonly background: 'var(--bar)'
  readonly color: 'var(--bar-text)'
  readonly borderTop: '1px solid var(--bar-border)'
  readonly boxShadow: 'var(--shadow-up)'
  readonly flexShrink: '0'
  readonly fontSize: 'var(--font-sm)'
}
