// GENERATED by scripts/gen-components.mjs from components.def.mjs — do not edit.
// Die Baustein-Optik als Stilobjekte (Inline-Styles). Dieselbe Definition wie components.css.
export const controlHeight = "calc(2 * var(--space-8) + var(--font-sm) * var(--leading-snug) + 2px)"

export const button = {
  "base": {
    "display": "inline-flex",
    "alignItems": "center",
    "gap": "var(--space-6)",
    "cursor": "pointer",
    "fontFamily": "inherit",
    "lineHeight": "var(--leading-snug)",
    "whiteSpace": "nowrap",
    "textDecoration": "none"
  },
  "sizes": {
    "xs": {
      "padding": "var(--space-2) var(--space-6)",
      "fontSize": "var(--font-xs)",
      "borderRadius": "var(--radius-xs)",
      "fontWeight": "600"
    },
    "sm": {
      "padding": "var(--space-4) var(--space-10)",
      "fontSize": "var(--font-sm)",
      "borderRadius": "var(--radius-sm)",
      "fontWeight": "600"
    },
    "md": {
      "padding": "var(--space-8) var(--space-14)",
      "fontSize": "var(--font-sm)",
      "borderRadius": "var(--radius-md)",
      "fontWeight": "500"
    }
  },
  "variants": {
    "primary": {
      "background": "var(--primary)",
      "color": "var(--on-primary)",
      "border": "1px solid var(--primary)"
    },
    "secondary": {
      "background": "var(--surface)",
      "color": "var(--text-heading)",
      "border": "1px solid var(--border)"
    },
    "ghost": {
      "background": "transparent",
      "color": "var(--text-muted)",
      "border": "1px solid transparent"
    },
    "danger": {
      "background": "var(--danger)",
      "color": "var(--on-primary)",
      "border": "1px solid var(--danger)"
    },
    "dangerOutline": {
      "background": "var(--surface)",
      "color": "var(--danger-text)",
      "border": "1px solid var(--danger-border)"
    },
    "admin": {
      "background": "var(--admin-soft)",
      "color": "var(--admin-text)",
      "border": "1px solid var(--admin-border)"
    }
  },
  "onBar": {
    "secondary": {
      "background": "transparent",
      "color": "var(--bar-text)",
      "border": "1px solid var(--bar-btn-border)"
    },
    "ghost": {
      "background": "transparent",
      "color": "var(--bar-text-muted)",
      "border": "1px solid transparent"
    },
    "admin": {
      "background": "var(--admin-tint)",
      "color": "var(--bar-text)",
      "border": "1px solid var(--admin-tint)"
    },
    "dangerOutline": {
      "background": "transparent",
      "color": "var(--bar-text)",
      "border": "1px solid var(--danger)"
    }
  }
}

export const input = {
  "base": {
    "padding": "var(--space-8) var(--space-10)",
    "borderWidth": "1px",
    "borderStyle": "solid",
    "borderColor": "var(--border)",
    "borderRadius": "var(--radius-md)",
    "fontSize": "var(--font-sm)",
    "background": "var(--surface)",
    "color": "var(--text)",
    "outline": "none",
    "boxSizing": "border-box",
    "fontFamily": "inherit",
    "lineHeight": "var(--leading-snug)"
  },
  "sm": {
    "padding": "var(--space-4) var(--space-8)",
    "borderRadius": "var(--radius-sm)",
    "fontSize": "var(--font-xs)"
  },
  "lg": {
    "padding": "var(--space-8) var(--space-12)",
    "fontSize": "var(--font-lg)"
  },
  "textarea": {
    "resize": "vertical",
    "lineHeight": "var(--leading-normal)",
    "minHeight": "4.5rem"
  },
  "mono": {
    "fontFamily": "var(--mono-font)"
  },
  "admin": {
    "borderColor": "var(--admin-border)"
  },
  "invalid": {
    "borderColor": "var(--danger)"
  },
  "readOnly": {
    "background": "var(--surface-hover)",
    "color": "var(--text-soft)"
  }
}

export const badge = {
  "base": {
    "display": "inline-flex",
    "alignItems": "center",
    "gap": "var(--space-4)",
    "borderRadius": "var(--radius-pill)",
    "fontWeight": "600",
    "lineHeight": "var(--leading-normal)",
    "whiteSpace": "nowrap",
    "fontVariantNumeric": "tabular-nums"
  },
  "sizes": {
    "sm": {
      "padding": "var(--space-1) var(--space-6)",
      "fontSize": "var(--font-xxs)"
    },
    "md": {
      "padding": "var(--space-2) var(--space-8)",
      "fontSize": "var(--font-xs)"
    }
  },
  "tones": {
    "neutral": {
      "soft": "var(--surface-hover)",
      "text": "var(--text-soft)",
      "solid": "var(--text-soft)",
      "onSolid": "var(--on-primary)"
    },
    "primary": {
      "soft": "var(--primary-soft)",
      "text": "var(--primary-strong)",
      "solid": "var(--primary)",
      "onSolid": "var(--on-primary)"
    },
    "success": {
      "soft": "var(--success-soft)",
      "text": "var(--success-text)",
      "solid": "var(--success)",
      "onSolid": "var(--on-primary)"
    },
    "danger": {
      "soft": "var(--danger-soft)",
      "text": "var(--danger-text)",
      "solid": "var(--danger)",
      "onSolid": "var(--on-primary)"
    },
    "warning": {
      "soft": "var(--warning-soft)",
      "text": "var(--warning-text)",
      "solid": "var(--warning)",
      "onSolid": "var(--warning-on-bar)"
    },
    "info": {
      "soft": "var(--info-soft)",
      "text": "var(--info)",
      "solid": "var(--info)",
      "onSolid": "var(--on-primary)"
    },
    "accent": {
      "soft": "var(--accent-soft)",
      "text": "var(--accent-text)",
      "solid": "var(--accent)",
      "onSolid": "var(--on-primary)"
    }
  },
  "outlineBorder": "var(--border)"
}

export const alert = {
  "base": {
    "padding": "var(--space-8) var(--space-12)",
    "borderRadius": "var(--radius-md)",
    "fontSize": "var(--font-sm)",
    "lineHeight": "var(--leading-snug)",
    "whiteSpace": "pre-wrap"
  },
  "tones": {
    "error": {
      "bg": "var(--danger-soft)",
      "fg": "var(--danger-text)",
      "border": "var(--danger-border)"
    },
    "warning": {
      "bg": "var(--warning-soft)",
      "fg": "var(--warning-text)",
      "border": "var(--warning)"
    },
    "success": {
      "bg": "var(--success-soft)",
      "fg": "var(--success-text)",
      "border": "var(--success)"
    },
    "info": {
      "bg": "var(--surface-muted)",
      "fg": "var(--text-heading)",
      "border": "var(--border)"
    }
  }
}

export const card = {
  "base": {
    "background": "var(--surface)",
    "border": "1px solid var(--border)",
    "borderRadius": "var(--radius-lg)",
    "padding": "var(--space-24)",
    "boxShadow": "var(--shadow-sm)"
  },
  "admin": {
    "border": "1px solid var(--admin-border)"
  }
}

export const panel = {
  "plain": {
    "background": "var(--surface)",
    "borderWidth": "1px",
    "borderStyle": "solid",
    "borderColor": "var(--border)",
    "borderRadius": "var(--radius-md)",
    "minWidth": "0"
  },
  "muted": {
    "background": "var(--surface-muted)",
    "borderRadius": "var(--radius-md)",
    "minWidth": "0"
  },
  "inset": {
    "background": "var(--bg)",
    "borderRadius": "var(--radius-md)",
    "minWidth": "0"
  },
  "pad": {
    "padding": "var(--space-10) var(--space-12)"
  }
}

export const actionBar = {
  "display": "flex",
  "alignItems": "center",
  "flexWrap": "wrap",
  "gap": "var(--space-8)",
  "padding": "var(--space-8) var(--space-14)",
  "background": "var(--bar)",
  "color": "var(--bar-text)",
  "borderTop": "1px solid var(--bar-border)",
  "boxShadow": "var(--shadow-up)",
  "flexShrink": "0",
  "fontSize": "var(--font-sm)"
}
