#!/usr/bin/env node
// Generates vars.js + vars.d.ts from tokens.css: every custom property as a
// typed constant, so a consumer writes `vars.textMuted` instead of the string
// 'var(--text-muted)'. A typo, or a name a new brand version removed, is then a
// COMPILE error in the consumer instead of a silently empty value in the browser.
//
//   node scripts/gen.mjs           # write
//   node scripts/gen.mjs --check   # exit 1 if the files are stale (npm run check)

import { readFileSync, writeFileSync, existsSync } from 'node:fs'

const root = new URL('..', import.meta.url)
const css = readFileSync(new URL('tokens.css', root), 'utf8')
const region = css.slice(css.indexOf('/* BEGIN tokens'), css.indexOf('/* END tokens */')).replace(/\/\*[\s\S]*?\*\//g, '')
const names = [...new Set([...region.matchAll(/(--[a-z0-9-]+)\s*:/g)].map(m => m[1]))]

const camel = n => n.slice(2).replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase())
const keys = new Map()
for (const n of names) {
  const k = camel(n)
  if (keys.has(k)) throw new Error(`${n} und ${keys.get(k)} ergeben denselben Schlüssel ${k}`)
  keys.set(k, n)
}

const head = '// GENERATED by scripts/gen.mjs from tokens.css — do not edit.\n'
const js = head +
  `/** Every brand custom property as a CSS value: vars.textMuted === 'var(--text-muted)'. */\n` +
  `export const vars = Object.freeze({\n${[...keys].map(([k, n]) => `  ${k}: 'var(${n})',`).join('\n')}\n})\n\n` +
  `/** Every brand custom property name, e.g. '--text-muted'. */\n` +
  `export const names = Object.freeze(${JSON.stringify(names, null, 2).replace(/"/g, "'")})\n`
const dts = head +
  `export declare const vars: {\n${[...keys].map(([k, n]) => `  readonly ${k}: 'var(${n})'`).join('\n')}\n}\n\n` +
  `/** A brand custom property name, e.g. '--text-muted'. */\n` +
  `export type BrandVarName =\n${names.map(n => `  | '${n}'`).join('\n')}\n\n` +
  `/** A reference to one, e.g. 'var(--text-muted)'. */\n` +
  `export type BrandVar = \`var(\${BrandVarName})\`\n\n` +
  `export declare const names: readonly BrandVarName[]\n`

const files = { 'vars.js': js, 'vars.d.ts': dts }
if (process.argv.includes('--check')) {
  const stale = Object.entries(files).filter(([f, s]) => !existsSync(new URL(f, root)) || readFileSync(new URL(f, root), 'utf8') !== s)
  if (stale.length) { console.error(`✗ ${stale.map(([f]) => f).join(', ')} passt nicht zu tokens.css — npm run gen`); process.exit(1) }
  console.log(`vars: ok (${names.length} Variablen)`)
} else {
  for (const [f, s] of Object.entries(files)) writeFileSync(new URL(f, root), s)
  console.log(`vars: geschrieben (${names.length} Variablen)`)
}
